from typing import Awaitable, Callable

class SmolgentError(RuntimeError): ...

class NativeAgent:
    def __init__(self, config_json: str) -> None: ...
    def arun(self, content_json: str,
             tools: list[tuple[str, Callable[[str], Awaitable[str]]]]) -> Awaitable[str]: ...
    def messages(self) -> str: ...
    def reset(self) -> None: ...

def set_api_key(keyring_id: str, api_key: str) -> None: ...
